server:
  port: 25000

spring:
  application:
    name: gulimall-seckill

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719

  redis:
    host: 127.0.0.1
    port: 6379

#  datasource:
#    druid:
#      db1:
#        url: jdbc:mysql://127.0.0.1:3306/rd?useUnicode=true&characterEncoding=utf-8&useSSL=false
#        username: root
#        password: 123456
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        #初始连接数 默认0
#        initial-size: 10
#        #最大连接数，默认8
#        max-active: 30
#        #最小闲置数
#        min-idle: 10
#        #获取连接的最大等待时间，单位毫秒
#        max-wait: 2000


#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

  #配置异步任务线程池
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50

  session:
    store-type: redis


#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
